### ISSUE TITLE
Прототип сервиса просмотра объявлений

### ISSUE THREAD

**Issue by slavb18** [ilb/adsviewer#1]
Вводное задание в проект. 
Внимание! Ввводное задание на frontend, последующие задания будут fullstack, для информации https://vercel.com/guides/nextjs-prisma-postgres

1. Запустить проект (npm install / npm run dev) 
2. Открыть форму http://localhost:3000/adsviewer/search
3 Доработать форму, добавив список объвлений (визуальный компонент)

![adsviewer](https://user-images.githubusercontent.com/2534896/110749274-5cc4c900-825a-11eb-9c41-6a0906476b45.jpg)

**Comment by Programmer-Pavel** [comment]
Клонировал репозиторий, при запуске порта: http://localhost:3000/adsviewer/search есть ошибки

**Comment by slavb18** [comment]
Какие ошибки?
Какая версия nodejs (`node -v`)?

**Comment by RustamSiraev** [comment]
Тоже ошибки...

Error: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

иногда 

AwilixResolutionError: Could not resolve 'search'.

https://cloud.mail.ru/public/jiTB/WkdKqW3Kb
https://cloud.mail.ru/public/hm4D/Sd238ykkM

node -v -> v14.15.4

**Comment by slavb18** [comment]
Приглашаю в чат, задайте вопросы там
https://t.me/joinchat/aHarJYhcJxJhOTYy

**Comment by slavb18** [comment]
> Тоже ошибки...
> 
> Error: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
> 
> иногда
> 
> AwilixResolutionError: Could not resolve 'search'.
> 
> https://cloud.mail.ru/public/jiTB/WkdKqW3Kb
> https://cloud.mail.ru/public/hm4D/Sd238ykkM
> 
> node -v -> v14.15.4

Приглашаю в чат ITPatrolChat, там можно задавать вопросы
https://t.me/joinchat/aHarJYhcJxJhOTYy
