### ISSUE TITLE
Реализовать загрузку ссылок на фотографии в базу

### ISSUE THREAD

**Issue by slavb18** [ilb/adsviewer#20]
Реализовать хранение ссылок на фотографии в базе, можно внтури поля json поля images или links

"images": [
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/214165/add.1519579814479e7737aa9fc/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/1020830/add.15195798364955902b3ad89/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/1020830/add.1519579852828a787958c5b/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/223159/add.151957988341218ecf1468a/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/1020830/add.1519579907282bbd3098d66/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/880603/add.1519579929830cd6a716ca9/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/776213/add.1519579949613df74b7f5f0/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/878469/add.15195800015746520e51e2b/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/762918/add.1519579983392039019cc79/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/773594/add.15195800264989957b4d509/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/366972/add.1519580060314df47f0d13f/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/762918/add.15195800950356bfefa77ae/large"
                },
                {
                    "imgurl": "https://avatars.mds.yandex.net/get-realty/212743/add.15195801352389d3f0e7930/large"
                }
            ],

**Comment by dmitryi698** [comment]
Не тот issue adsLoader поправил
