### ISSUE TITLE
Подключить поиск в списках

### ISSUE THREAD

**Issue by slavb18** [ilb/adsviewer#22]
Подключить поиск в списках, пример здесь:

https://github.com/ilb/uniformscomponents/blob/f53aa04fac72b337847b2d1b5f4d9864df0e9294/AppForm.jsx#L41-L43

Можно использовать DropDown с опцией search
https://react.semantic-ui.com/modules/dropdown/#types-search-selection

**Comment by enariavishenda** [comment]
fixes #22
