### ISSUE TITLE
Форма не заполняется при открытии ссылки с параметрами

### ISSUE THREAD

**Issue by slavb18** [ilb/adsviewer#23]
Форма не заполняется при открытии ссылки с параметрами

adsviewer/autoform?case=transport&carmanufacturer=Hyundai&carmodel=Solaris&year=2011&body=%D0%BF%D0%B8%D0%BA%D0%B0%D0%BF&transmission=%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82&persons=1&horse=106&volume=1.4&region=bashkortostan

![image](https://user-images.githubusercontent.com/2534896/114130605-fe9b0c80-9911-11eb-8f70-81aa416aa6b3.png)

**Comment by enariavishenda** [comment]
fixes #23
