### ISSUE TITLE
Не работает загрузка объявлений

### ISSUE THREAD

**Issue by slavb18** [ilb/adsviewer#35]
dateFrom: 11-04-2021 12:34:00
dateFrom: 11-04-2021 12:49:00
https://ads-api.ru/main/api?user=dima2prog@gmail.com&token=7898911c474142c34cae4d840cb149e9&category_id=22&date1=11-04-2021+12:34:00&date2=11-04-2021+12:49:00
Send query to server
(Provider)Get server ansver 200
Loaded...
dateFrom: 11-04-2021 12:34:00
dateFrom: 11-04-2021 12:49:00
https://ads-api.ru/main/api?user=dima2prog@gmail.com&token=7898911c474142c34cae4d840cb149e9&category_id=22&date1=11-04-2021+12:34:00&date2=11-04-2021+12:49:00
Send query to server
(Provider)Get server ansver 200
А в таблице ads пусто

**Comment by dmitryi698** [comment]
fixes #39
